### ISSUE TITLE
Gearman-Client-Async tests hang since Gearman > 1.130.004

### ISSUE THREAD

**Issue by ppisar** [p-alik/perl-Gearman#10]
I noticed Gearman-Client-Async-0.94 started to fail tests after upgrading Gearmean from 1.130.004 to 2.002.003 <https://rt.cpan.org/Public/Bug/Display.html?id=120306>.

I bisected the failure to Gearman's commit:

```
commit 049bc8fb998759ec0435e2879a456064b9f28170
Author: Alexei Pastuchov <info@maximka.de>
Date:   Sun Jul 24 18:48:49 2016 +0200

    bug fix: worker provide all parameters to super
```

Do you have an idea if this is a bug in new Gearman or Gearman-Client-Async uses Gearman in a wrong way?

**Comment by p-alik** [comment]
Oh, I'm sorry. I'll fix it as soon as possible.

**Comment by p-alik** [comment]
@ppisar, what kind of `gearmand` do you use for testing purpose?
gearman.org or [Gearman::Server](https://metacpan.org/pod/Gearman::Server)

**Comment by ppisar** [comment]
On Mon, Feb 20, 2017 at 12:56:16PM -0800, Алексей Пастухов wrote:
> @ppisar, what kind of `gearmand` do you use for testing purpose?
> gearman.org or [Gearman::Server](https://metacpan.org/pod/Gearman::Server)
>
Gearman-Server-v1.130.1.

**Comment by p-alik** [comment]
After little changes commited in [this branch](https://github.com/p-alik/perl-Gearman/tree/issue-10) `allinone.t` runs fine in my environment.

```bash
$ prove -I ../Gearman-Server/lib/ -I ../perl-Gearman/lib/ -lv t/allinone.t
t/allinone.t ..
1..2
ok 1 - Got both responses
ok 2 - 12 status messages
ok
All tests successful.
```
May you test it please.

**Comment by ppisar** [comment]
On Wed, Mar 01, 2017 at 11:54:17PM -0800, Алексей Пастухов wrote:
> After little changes commited in [this
> branch](https://github.com/p-alik/perl-Gearman/tree/issue-10) `allinone.t`
> runs fine in my environment.
[...]
> May you test it please.
> 
Thanks for the fix. I tested it and it works for me now.

-- Petr

**Comment by p-alik** [comment]
cool, thanks for testing.
Bug fixing will be a part of next alpha _v2.003_002_, I'll release this evening.

**Comment by p-alik** [comment]
Since Gearman::Client v2.003.001 is released to [CPAN](https://metacpan.org/release/PALIK/Gearman-2.003.001) the issue is done
