### ISSUE TITLE
unreliable tests

### ISSUE THREAD

**Issue by p-alik** [p-alik/perl-Gearman#14]
1.  t/14-sleep.t
When I was installing/testing 2.004.001 using 'cpan', t/14-sleep.t hanged
during either test #4 or #5 ("4/?" was displayed on the screen).... After I
gave up and hit control-C, I ran the test again, and then it worked.
1.  t/50-wait_timeout.t
http://www.cpantesters.org/cpan/report/5db73e0c-1589-11e7-807f-f398cc11fead
```
    #   Failed test 'timeout'
    #   at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.25.3/f11c/lib/site_perl/5.25.3/Test/Timer.pm line 24.
    # Test exceeded specified threshold
    # Looks like you failed 1 test of 10.

#   Failed test 'wait with timeout'
#   at t/50-wait_timeout.t line 65.
# Looks like you failed 1 test of 4.
t/50-wait_timeout.t ............. 
```

**Comment by esabol** [comment]
Just some context for (1) in the above post: It occurred on CentOS 7.3 using /usr/bin/perl (v5.16.3) when tested using the `cpan` command. I could not reproduce it running "make test" from the command line outside of `cpan`, but I didn't try multiple times either.

**Comment by esabol** [comment]
These tests have been quite reliable lately. I'm not sure what caused them to be unreliable before, but I'm satisfied that this is likely no longer a problem. Are you still getting t/50-wait_timeout.t failures on cpantesters? If not, feel free to close this issue.

**Comment by p-alik** [comment]
[http://matrix.cpantesters.org/?dist=Gearman%202.004.009](cpantesters) doesn't got some fail reports for 2.004.009. Here are latest reports with regard to `50-wait_timeout.t`. 

> Gearman-2.004.007:
> - amd64-freebsd / 5.20.0:
>   - FAIL http://www.cpantesters.org/cpan/report/bf58ddf4-4564-11e7-b49d-974c075893f8
> 
> - x86_64-linux / 5.22.1:
>   - FAIL http://www.cpantesters.org/cpan/report/034a8462-451b-11e7-a0d3-fbda2e7d480a

**Comment by p-alik** [comment]
we'll reopen the issue if necessary
