### ISSUE TITLE
Taskset->add_task does not support payload > 16K if SSL socket

### ISSUE THREAD

**Issue by p-alik** [p-alik/perl-Gearman#16]
The issue is related to 9545f18b9b60a87fc977c2041c174f701d778a1a

`syswrite` in [add_task](https://github.com/p-alik/perl-Gearman/blob/v2.004.005/lib/Gearman/Taskset.pm#L276) should be replaced by
```
my $rv = Gearman::Util::send_req($jssock, \$req);
```

**Comment by p-alik** [comment]
done but not released yet

**Comment by esabol** [comment]
I added a comment on the commit 56b7a1f6b7b87ed1fcb047c8100a608917747b3c.
