### ISSUE TITLE
Gearman-2.004.008 tests report "Unknown option: log-file"

### ISSUE THREAD

**Issue by ppisar** [p-alik/perl-Gearman#22]
Gearman-2.004.008 added --log-file option to server invocation when running tests. But running the tests against Gearman-Server-1.130.1 results in warnings about an unknown option:

~~~
t/01-object.t ................... ok
Unknown option: log-file
t/02-client.t ................... ok
Unknown option: log-file
Unknown option: log-file
Unknown option: log-file
Unknown option: log-file
Unknown option: log-file
~~~

**Comment by p-alik** [comment]
Thanks for reporting, @ppisar.
Bug fixing should be included in next release.

**Comment by p-alik** [comment]
done in [2.004.009](https://metacpan.org/pod/release/PALIK/Gearman-2.004.009/lib/Gearman/Client.pm)
