### ISSUE TITLE
Pod typo

### ISSUE THREAD

**Issue by esabol** [p-alik/perl-Gearman#26]
https://github.com/p-alik/perl-Gearman/blob/4312dba96139d53887fa9ba9035b6e190979053c/lib/Gearman/Objects.pm#L146

s/getr/get/;

**Comment by p-alik** [comment]
Thank you, @esabol.

**Comment by p-alik** [comment]
[v2.004.010](https://github.com/p-alik/perl-Gearman/releases/tag/v2.004.010) was uploaded to CPAN.
