### ISSUE TITLE
Gearman::Client problem with strings flagged as UTF8

### ISSUE THREAD

**Issue by esabol** [p-alik/perl-Gearman#27]
I'm not sure if this is a bug or not? What do you think? If it's not a bug, I will close the issue.

I recently modified my Gearman clients to read some configuration information from an XML file using XML::LibXML. Afterward, I started getting the following error in my clients with 2.004.009 whenever I called do_task() with a string based on one of the values I parsed from the XML file:
```
reading response packet failed: timeout at /path/to/Gearman-2.004.009/blib/lib/Gearman/Client.pm line 354.
```
If I specified the string in the code instead of parsing the XML file to get the string, Gearman::Client worked just fine. That was very perplexing for a while. Eventually, I compared the two variables using
Devel::Peek and discovered that the string that caused the error had the UTF8 flag set:
```
$string1 = SV = PVMG(0x1f394e0) at 0x1c99438
  REFCNT = 1
  FLAGS = (PADMY,POK,pPOK,UTF8)
  IV = 0
  NV = 0
  PV = 0x1f58850 "blahblahblah..."\0 [UTF8 "blahblahblah..."]
  CUR = 33
  LEN = 40
```
Compare that with the string that worked:
```
$string2 = SV = PVMG(0x1f398d0) at 0x1a902b0
  REFCNT = 1
  FLAGS = (PADMY,GMG,SMG,pPOK)
  IV = 0
  NV = 0
  PV = 0x1eba390 "blahblahblah..."\0
  CUR = 33
  LEN = 40
  MAGIC = 0x19287f0
    MG_VIRTUAL = &PL_vtbl_taint
    MG_TYPE = PERL_MAGIC_taint(t)
```
I modified my client code to call utf8::downgrade($string1), and everything started working again.

Maybe the documentation for Gearman::Client should mention that it does not work with UTF-8 strings?

The error message I was getting wasn't very useful. Can anything be done about that?

Right before submitting this issue, I googled "IO::Socket::SSL utf8" and found this issue, which may be related:
https://rt.cpan.org/Public/Bug/Display.html?id=98372

**Comment by p-alik** [comment]
> I'm not sure if this is a bug or not?
There is now way to certainly answer the question without utf8 tests. I'll add it soon and let you know the result. 

> Right before submitting this issue, I googled "IO::Socket::SSL utf8" and found this issue, which may be related:
> https://rt.cpan.org/Public/Bug/Display.html?id=98372

As mentioned in [IO::Socket::SSL issue 98372](https://rt.cpan.org/Public/Bug/Display.html?id=98372) Net::SSLeay seems to cause it.

> Maybe the documentation for Gearman::Client should mention that it does not work with UTF-8 strings?

Indeed, this will be done for both client and worker implementations.

**Comment by esabol** [comment]
>> I'm not sure if this is a bug or not?
> There is now way to certainly answer the question without utf8 tests. I'll add it soon and let you know the result.

I was more referring to the philosophical question of whether or not UTF8-flagged payloads _should_ be supported or not. The IO::Socket::SSL and Net::SSLeay developers don't seem to think so?

**Comment by p-alik** [comment]
fa66ba71c6 adds a note in Client.pm with regard to lack of UTF-8 support.
If it appears convenient to you, I'll add the same in Worker.pm.

**Comment by esabol** [comment]
That's fine with me. Thank you!

**Comment by p-alik** [comment]
[v2.004.010](https://github.com/p-alik/perl-Gearman/releases/tag/v2.004.010) was uploaded to CPAN.
