### ISSUE TITLE
Gearman::Client: "on_fail" is not triggered on timeout

### ISSUE THREAD

**Issue by hidden-primary-net** [p-alik/perl-Gearman#33]
When handing in a `timeout` to a `do_task` call of a Gearman::Client object the given "on_fail" callback is currently not triggered when the timeout elapsed as told by the [`Gearman::Task` documentation](../blob/upstream/lib/Gearman/Task.pm#L137). Please see the prove: https://github.com/hidden-primary-net/perl-Gearman/commit/cb9d3c6a6ac75f4136b97d82b84667c8551d66b8.

**Comment by p-alik** [comment]
done in #34
