### ISSUE TITLE
Gearman::Taskset: Wrong error reason

### ISSUE THREAD

**Issue by hidden-primary-net** [p-alik/perl-Gearman#35]
With issue #33 fixing the missing call of the `on_fail` callback I suggested an error reason containing the given timeout value. Unfortunately I missed the fact that the given value is manipulated. Instead of telling the given timeout value the user encounters a message like this:

    Task task_that_does_not_exist elapsed timeout [1514988291.35953s]

The current time was added to the given timeout value.
This is not the (my) intended behaviour, I'll create a pull request fixing this issue.

**Comment by esabol** [comment]
I think this issue can be closed now with the release of v2.004.012?

**Comment by p-alik** [comment]
indeed, the issue is done
