### ISSUE TITLE
Deep recursion on subroutine "Gearman::Util::_read_sock" warning with large task payloads

### ISSUE THREAD

**Issue by esabol** [p-alik/perl-Gearman#38]
For very large responses to `do_task()` (> 100 MB), Perl prints the following warning:
```
Deep recursion on subroutine "Gearman::Util::_read_sock" at /path/to/Gearman/Util.pm line 224.
```
This seems harmless enough (the response is completely intact). Based on my googling, this warning is issued when you reach 100 levels of recursion.

Since `_read_sock` heavily utilizes recursion, I think adding
```Perl
no warnings 'recursion';
```
on line 7 of Gearman/Util.pm might be a good idea. It doesn't seem to be possible to turn this warning off elsewhere in one's code. My client code that calls Gearman::* can't turn it off, for example. What do you think?

**Comment by p-alik** [comment]
Thank you, @esabol.
Putting `no warnings` pragma inside of `Gearman::Util::_read_sock` solves the issue also.
If you haven't any objections, I would rather prefer this variant.

**Comment by esabol** [comment]
I'm worried that might impact performance doing that?

**Comment by p-alik** [comment]
my version would be slightly slower.
```text
Benchmark: running A, AA for at least 5 CPU seconds...
         A:  5 wallclock secs ( 5.47 usr +  0.00 sys =  5.47 CPU) @  0.91/s (n=5)
        AA:  5 wallclock secs ( 5.54 usr +  0.00 sys =  5.54 CPU) @  0.90/s (n=5)
   s/iter  AA   A
AA   1.11  -- -1%
A    1.09  1%  --
```
[no-warning-benchmark.tar.gz](https://github.com/p-alik/perl-Gearman/files/1806534/no-warning-benchmark.tar.gz)

**Comment by esabol** [comment]
Not much of a difference, but I would still put it at the top of the file instead of in the `sub`.

**Comment by p-alik** [comment]
[v2.004.014](https://github.com/p-alik/perl-Gearman/releases/tag/v2.004.014) should be available on CPAN soon.
