### ISSUE TITLE
Multiple gearman servers and redundancy

### ISSUE THREAD

**Issue by vkatsikaros** [p-alik/perl-Gearman#39]
Hi

The gearman [documentation](http://gearman.org/) says on multiple servers:
> You are able to run multiple job servers and have the clients and workers connect to the first available job server they are configured with. This way if one job server dies, clients and workers automatically fail over to another job server.

When we experimented with one of many gearman servers to be stopped we experienced broadcasting to be 100 to 200 times slower, compared to all gearman server running. 

I would like to ask if this is the expected behavior and/or if there is something additional we could do to improve the situation:

Results
--------
- client.pl 2 out of 2 servers running
`timethis 500:  1 wallclock secs ( 0.23 usr +  0.04 sys =  0.27 CPU) @ 1851.85/s (n=500)`
- client.pl: 1 out of 2 servers running (1 stopped)
`timethis 500: 247 wallclock secs ( 0.36 usr +  0.07 sys =  0.43 CPU) @ 1162.79/s (n=500)` and 50% of tasks are processed

- client: 3 out of 3 servers running
`timethis 500:  1 wallclock secs ( 0.18 usr +  0.02 sys =  0.20 CPU) @ 2500.00/s (n=500)`
- client: 2 out of 3 servers running  (1 stopped)
`timethis 500: 155 wallclock secs ( 0.18 usr +  0.02 sys =  0.20 CPU) @ 2500.00/s (n=500)` and 66% of tasks are processed

client.pl
------

```perl
use Benchmark;
use Gearman::Client;
use Data::UUID;
use Storable qw( freeze );
$i = 1;
my $uuid_gen = Data::UUID->new;
timethis (500, \&gearman_client);

sub gearman_client {
  my $client = Gearman::Client->new;
  $client->job_servers(
    { host => '10.30.5.41', port => 4900 },
    { host => '10.30.6.194', port => 4900 },
    { host => '10.30.6.108', port => 4900 }, # comment out for 2 gearman servers setup
  );
  my $serialized = freeze([ 3, 5 ]);
  my $task = Gearman::Task->new(
    'sum',
    \$serialized,
    {
      uniq => $uuid_gen->create_str,
    }
  );
  $client->dispatch_background($task);
  print "Sum of tasks sent $i\n";
  $i++
}
```

worker.pl
------

```perl
use Gearman::Worker;
use Storable qw( thaw );
use List::Util qw( sum );
$i = 1;
my $worker = Gearman::Worker->new;
$worker->job_servers(
  { host => '10.30.5.41', port => 4900 },
  { host => '10.30.6.194', port => 4900 },
  { host => '10.30.6.108', port => 4900 }, # comment out for 2 gearman servers setup
);
$worker->register_function(
  'sum',
  sub {
    sum @{ thaw($_[0]->arg) };
    print "Sum of tasks received $i\n";
    $i++;
  }
);
$worker->work while 1;

```

Setup
------
- gearman C server: 1.1.18
- perl client: 2.004.014
- server compiled with:
```
wget https://github.com/gearman/gearmand/releases/download/1.1.18/gearmand-1.1.18.tar.gz
./configure --enable-ssl
make
make install
```
- on Ubuntu 14.04.5 LTS 
- perl v5.26.2 
```
Summary of my perl5 (revision 5 version 26 subversion 2) configuration:
   
  Platform:
    osname=linux
    osvers=3.13.0-145-generic
    archname=x86_64-linux
    uname='linux ip-10-0-0-112 3.13.0-145-generic #194-ubuntu smp thu apr 5 15:20:44 utc 2018 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/opt/perlbrew/perls/perl-5.26.2 -Aeval:scriptdir=/opt/perlbrew/perls/perl-5.26.2/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion=''
    gccversion='4.8.4'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.19.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.19'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    Devel::PatchPerl 1.48
  Built under linux
  Compiled at May  4 2018 17:12:37
  %ENV:
    PERL5LIB="/a_directory"
  @INC:
    /a_directory
    /opt/perlbrew/perls/perl-5.26.2/lib/site_perl/5.26.2/x86_64-linux
    /opt/perlbrew/perls/perl-5.26.2/lib/site_perl/5.26.2
    /opt/perlbrew/perls/perl-5.26.2/lib/5.26.2/x86_64-linux
    /opt/perlbrew/perls/perl-5.26.2/lib/5.26.2
```

**Comment by p-alik** [comment]
I guess default [command_timeout](https://github.com/p-alik/perl-Gearman/blob/master/lib/Gearman/Client.pm#L150) is blame for the issue. 

Worker's [register_function](https://github.com/p-alik/perl-Gearman/blob/master/lib/Gearman/Worker.pm#L436) also supports setting of timeout.

**Comment by vkatsikaros** [comment]
Thanks for the comments @p-alik 

I did experiments with the default timeout (30) and a timeout of 1. However, I noticed that there is a difference (regardless of timeout) depending on the meaning of "server running":

1.  the machine hosting gearmand is turned on and accepts network connections but the gearmand server is not running
2. the machine hosting gearmand is turned off and the IP is not pointing to another machine

It turns out my previous issue comment was about the 2nd case. With a timeout of both 1 and 30 I see the same _unexpected_ behavior: the client becoming 100-200 times slower

Regarding the 1st case, with a timeout of both 1 and 30 I see the same _expected_ behavior: the client runs equally fast.

Any ideas?

Results
-------

timeout 1:
* client: 2 out of 2 servers running: `timethis 500:  1 wallclock secs ( 0.23 usr +  0.04 sys =  0.27 CPU) @ 1851.85/s (n=500)`
* client: 1 out of 2 servers running (not running: machine turned on and gearmand not running): `timethis 500:  1 wallclock secs ( 0.13 usr +  0.02 sys =  0.15 CPU) @ 3333.33/s (n=500)`
* client: 1 out of 2 servers running (not running: machine turned off): `timethis 500: 247 wallclock secs ( 0.36 usr +  0.07 sys =  0.43 CPU) @ 1162.79/s (n=500)`

timeout 30:
* client: 2 out of 2 servers running `timethis 500:  1 wallclock secs ( 0.17 usr +  0.02 sys =  0.19 CPU) @ 2631.58/s (n=500)`
* client: 1 out of 2 servers running (not running: machine turned on and gearmand not running): `timethis 500:  1 wallclock secs ( 0.13 usr +  0.04 sys =  0.17 CPU) @ 2941.18/s (n=500)`
* client: 1 out of 2 servers running (not running: machine turned off) `timethis 500: 238 wallclock secs ( 0.22 usr +  0.04 sys =  0.26 CPU) @ 1923.08/s (n=500)`

client.pl
----------------------------------
```perl
use strict;
use warnings;
use Benchmark;
use Gearman::Client;
use Data::UUID;
use Storable qw( freeze );
my $i = 1;
my $timeout = 1;
my $uuid_gen = Data::UUID->new;
timethis (500, \&gearman_client);

sub gearman_client {
  my $client = Gearman::Client->new(command_timeout => $timeout);
  $client->job_servers(
    { host => '10.30.5.41', port => 4900 },
    { host => '10.30.6.104', port => 4900 },
  );
  my $serialized = freeze([ 3, 5 ]);
  my $task = Gearman::Task->new(
    'sum',
    \$serialized,
    {
      uniq => $uuid_gen->create_str,
    }
  );
  $client->dispatch_background($task);
  print "Sum of tasks sent $i\n";
  $i++;
}
```

worker.pl
----------------------------------
```perl
use strict;
use warnings;
use Gearman::Worker;
use Storable qw( thaw );
use List::Util qw( sum );
my $i = 1;
my $timeout = 1;
my $worker = Gearman::Worker->new;
$worker->job_servers(
  { host => '10.30.5.41', port => 4900 },
  { host => '10.30.6.104', port => 4900 },
);
$worker->register_function(
  'sum',
  $timeout,
  sub {
    sum @{ thaw($_[0]->arg) };
    print "Sum of tasks received $i\n";
    $i++;
  }
);
$worker->work while 1;
```

**Comment by p-alik** [comment]
> Regarding the 1st case, with a timeout of both 1 and 30 I see the same expected behavior: the client runs equally fast.

I'm sorry for misleading you.
 
> Any ideas?

[socket initialisation](https://github.com/p-alik/perl-Gearman/blob/master/lib/Gearman/Objects.pm#L192) is much faster if resource is available.

**client.pl** used for testing
```perl
use strict;
use warnings;
use Benchmark;
use Gearman::Client;
use Data::Dump "dump";

my $timeout = 1;
my $client = Gearman::Client->new(command_timeout => $timeout);
$client->job_servers(
  { host => 'localhost', port => 4730 },
);

timethis (500, \&gearman_sock);

sub gearman_sock {
  $client->debug(1);
  foreach ($client->job_servers) {
    print dump($_), $/;
    $client->socket($_);
  }
}

```
* no `gearmand` service `timethis 500:  0 wallclock secs ( 0.06 usr +  0.03 sys =  0.09 CPU) @ 5555.56/s (n=500)`
* with `gearmand` service `timethis 500:  0 wallclock secs ( 0.10 usr +  0.04 sys =  0.14 CPU) @ 3571.43/s (n=500)`

**Comment by vkatsikaros** [comment]
@p-alik thanks for the comments. So I understand, there no a solution with "perl-Gearman" to improve the situation if the machine with gearmand is not running. I guess the only fallback option is to somehow to a "ping" the machines in my client code and dynamically set the `$client->job_servers`. Any thoughts about a "perl-Gearman" solution?

**Comment by p-alik** [comment]
> Any thoughts about a "perl-Gearman" solution?

Unfortunately I haven't any solution for the issue. In my opinion it's an issue of application/environment and not of perl-Gearman. There is no issue at all if Gearman::{Client,Worker} is initialised with improved list of `gearmand`-instances.

But if you have any idea to improve perl-Gearman, please share it.

**Comment by vkatsikaros** [comment]
Thanks @p-alik !
