### ISSUE TITLE
Gearman::Client undocumented options

### ISSUE THREAD

**Issue by vkatsikaros** [p-alik/perl-Gearman#40]
It seems there are 2 undocumented [options](https://github.com/p-alik/perl-Gearman/blob/v2.004.014/lib/Gearman/Client.pm#L149:L150) in the [Gearman::Client perdoc section](https://github.com/p-alik/perl-Gearman/blob/v2.004.014/lib/Gearman/Client.pm#L64:L91)
* backoff_max
* command_timeout

**Comment by p-alik** [comment]
enhancement is released in 2.004.015
https://metacpan.org/changes/release/PALIK/Gearman-2.004.015
