### ISSUE TITLE
missing documentation of Gearman::Task's on_-callbacks

### ISSUE THREAD

**Issue by andk** [p-alik/perl-Gearman#43]
RTFS reveals the number of on_xxx fields is 8, but the manpage covers only 5. Three are missing:

``` text
| on_complete   | ✓ |
| on_data       |   |
| on_fail       | ✓ |
| on_exception  |   |
| on_warning    | ✓ |
| on_retry      | ✓ |
| on_status     | ✓ |
| on_post_hooks |   |
```

**Comment by p-alik** [comment]
https://github.com/p-alik/perl-Gearman/blob/4f221ba9a18dd52de9c54f1fc8731b3e614e743c/t/04-task.t#L153
@andk, do you have any objection to solve it in this manner https://github.com/p-alik/perl-Gearman/commit/43e6602959e36eed4c9885943acc7ccb68b83133?

**Comment by p-alik** [comment]
@andk, documentation for two of three fields has been added yet.
 
- `on_data` 3a666571177bdf480de67fbf358e29ab8981956a
- `on_exception`
  - cffe74b617dbcf71e82d085590784e3197ba5590
  - ec12ee01c8356b80c8d55394f714e1e5242d0052

There is no internal use of `on_post_hooks` at all. [Gearman::Client::Async](https://github.com/p-alik/Gearman-Client-Async/blob/master/lib/Gearman/Client/Async.pm#L175) seems to be the only consumer of the method. I would prefer to leave it undocumented.

**Comment by p-alik** [comment]
Please, reopen the issue, if you have any objections.
