### ISSUE TITLE
Support low priority tasks

### ISSUE THREAD

**Issue by davel** [p-alik/perl-Gearman#6]
The protocol supports a "low" priority level, in addition to "high" and "normal", which the client currently implements. See https://github.com/gearman/gearmand/blob/33fccc5390dc67afc2a3fea36ea0bfecfe36b44b/PROTOCOL#L165

Could we add support for low priority tasks in the client?

**Comment by p-alik** [comment]
thanks for pointing to the issue @davel. It should be done soon.

**Comment by p-alik** [comment]
@davel, the issue is solved in 099053a. I'll close it as soon as new version is uploaded to cpan

**Comment by p-alik** [comment]
@davel, the issue is done. This is a part of [2.003_001](https://metacpan.org/pod/release/PALIK/Gearman-v2.003_001/lib/Gearman/Client.pm) release.

**Comment by davel** [comment]
Awesome, thank you!
